# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will runcs
on: push 
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "builds"
  build:
    # The type of runner that the job will run onn
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: auto increment version tag  
        id: auto-version-increment
        run: bash ./.github/workflows/auto-increment-v.sh

     
