# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push 
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "builds"
  build:
    # The type of runner that the job will run ona
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: auto increment version tag  
        id: auto-version-increment
        run: bash ./.github/workflows/auto-increment-v.sh

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Lookup version
        id: version-lookup
        run: bash ./.github/workflows/version-lookup.sh

      - name: Increment version
        id: version-increment
        run: bash ./.github/workflows/version-increment.sh
        env:
          scheme: semver
          current_version: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
          
      - name: Release versions
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        with:
            draft: false
            prerelease: false
            tag_name: "${{ steps.version-increment.outputs.VERSION }}"


      
