# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issue_comment:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Comment Tags
        id: fetch-tags
        run: |
             TAGS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" | jq -r '.[] | select(.body | test("tags:")) | .body')
             echo "$TAGS" > tags.txt
        env:
             GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Lookup version
        id: version-lookup
        run: bash ./.github/workflows/version-lookup.sh

      - name: Increment version
        id: version-increment
        run: bash ./.github/workflows/version-increment.sh
        env:
          scheme: semver
          current_version: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
          
      - name: Release versions
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        with:
            draft: false
            prerelease: false
            tag_name: "${{ steps.version-increment.outputs.VERSION }}"


      
